import turtle
s=turtle.Screen()
s.bgcolor("magenta")
t=turtle.Turtle()
t.pen(pencolor="blue",fillcolor="cyan",pensize=10,speed=9)
t.begin_fill()
    #t.forward(100)
    #t.rt(90)
    #t.forward(100)
    #t.rt(90)
    #t.forward(100)
    #t.rt(90)
    #t.forward(100)
    #t.rt(90)
for i in range(0,4):
    t.forward(100)
    t.rt(90)
t.end_fill()
s.exitonclick()
